[project]
site_name = "SliDesk"
site_description = "A speaker companion"
site_author = "SliDesk Team"
site_url = "https://slidesk.link"
copyright = """
Copyright &copy; 2026 SliDesk
"""
repo_url = "https://github.com/slidesk/slidesk"
repo_name = "slidesk/slidesk"

[project.theme]
logo = "_media/icon.svg"
language = "en"
features = [
    "announce.dismiss",
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
    "content.footnote.tooltips",
    "content.tabs.link",
    "content.tooltips",
    #"navigation.expand",
    "navigation.footer",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.path",
    "navigation.prune",
    "navigation.sections",
    "navigation.tabs",
    "navigation.tabs.sticky",
    "navigation.top",
    "navigation.tracking",
    "search.highlight",
]

[project.theme.icon]
repo = "fontawesome/brands/github"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[project.theme.font]
text = "Inter"
code = "Jetbrains Mono"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/slidesk/slidesk"

[[project.extra.social]]
icon = "fontawesome/brands/bluesky"
link = "https://bsky.app/profile/slidesk.link"
